version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-application"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tlym0a4lxt65"
s3_prefix = "sam-application"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

